<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

| **Term**       | **Brief Description**                                                                                    |
| -------------- | -------------------------------------------------------------------------------------------------------- |
| **Subsetting** | Selecting a portion of a dataset (like specific rows, columns, or values) using conditions or positions. |
| **Indexing**   | Accessing elements in a data structure using positions.                     |
| **Slicing**    | Selecting a range of elements using notation.                     |
| **Masking**    | Using True/False to select or filter elements from an array based on a condition.      |


In [7]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers = np_array_2d[:, 0].astype(int)
mask = numbers % 2 == 1
odd_letters = np_array_2d[mask, 1]

print(odd_letters)  # Output: ['A' 'C' 'E' 'G' 'I']


['A' 'C' 'E' 'G' 'I']


In [8]:
import numpy as np

arr = np.array([
    [66, 50, 57, -1, -1],
    [92, -1, 88, -1, -1],
    [75, -1, -1, 76, -1],
    [-1, 51, 87, -1, -1],
    [71, -1, 67, -1, 69]
])


In [9]:
modified = arr.copy()

modified[modified < 50] = -1
modified[modified > 50] = 1
modified[modified == 50] = 0


In [10]:
print(modified)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
